# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

require 'rubygems'
require 'bundler/setup'

require 'rails/all'
require 'simple_form'

require 'dead_simple_cms'
require File.expand_path('../setup', __FILE__)

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

# Datbase setup.
require 'sqlite3'
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "dead_simple_cms.sqlite3")
ActiveRecord::Base.silence do
  ActiveRecord::Migration.verbose = false
  ActiveRecord::Schema.define :version => 0 do
    create_table :dead_simple_cms, :force => true do |t|
      t.string :key
      t.text :value
      t.timestamps
    end
    add_index :dead_simple_cms, :key, :unique => true
  end
end

#RSpec::Matchers.define :have_only_tag_values do |expected|
#  match do |actual|
#    actual = actual.tags if actual.class.respond_to?(:taggable?) && actual.class.taggable?
#    same_elements?(actual.map(&:value), expected)
#  end
#end
#
#RSpec::Matchers.define :have_same_elements do |expected|
#  match do |actual|
#    same_elements?(actual, expected)
#  end
#end